# Generated by Django 3.2.4 on 2021-06-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='defaults.jpg', upload_to='post_pics'),
        ),
    ]
