# Generated by Django 3.1.7 on 2021-09-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210901_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='defaults.jpg', upload_to='profile_pics'),
        ),
    ]
