# Generated by Django 3.2.8 on 2021-10-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='Urla',
        ),
    ]
